services:
    pgdatabase:
        image: postgres:13
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=ny_taxi
        ports:
            - 5432:5432
        networks:
            - pg-network
        volumes:
            - ./01-docker-terraform/docker_intro/ny_taxi_postgres_data:/var/lib/postgresql/data:rw

    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - 8080:80
        networks:
            - pg-network
        volumes:
            - ./01-docker-terraform/docker_intro/pg-admin-data:/var/lib/pgadmin:rw

networks:
    pg-network:
        driver: bridge
